# Generated by Django 4.2.6 on 2023-10-22 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('detalle', models.CharField(max_length=1000)),
                ('detalle_corto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('S', 'Suspensión de actividad'), ('C', 'Suspensión de clase'), ('I', 'Información')], max_length=1)),
                ('visible', models.BooleanField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_ultima_modificacion', models.DateTimeField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.entidad')),
                ('modificador_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_modificados', to=settings.AUTH_USER_MODEL)),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_publicados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
